version: '3.3'

services:
      
  frontend:
    build:
      context: ./angular-frontend
      dockerfile: Dockerfile
    container_name: angular-frontend
    image: angular-frontend
    restart: always
    volumes:
      - ./angular-frontend/:/app
    ports:
      - 80:4200
    depends_on:
      - backend
    links:
      - backend
      - mysql_db
    networks:
      - data_network

  backend:
    build:
      context: ./python_backend
      dockerfile: Dockerfile
    container_name: backend
    image: backend
    restart: always
    volumes:
        - ./python_backend/:/app
    ports:
        - 8000:8080
    depends_on:
      - mysql_db
    links:
      - mysql_db
    networks:
      - data_network

  mysql_db:
    container_name: mysqlDB
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_USER: root
      MYSQL_DB: test_db
    ports:
      - 3304:3304
    networks:
      - data_network
networks:
  data_network:
    driver: bridge